[package]
name = "col"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.5.1"
chumsky = "0.11.1"
logos = "0.15.1"
owo-colors = "4.2.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34+deprecated"
